"""
Urban Pulse AI — City Configuration
Production-grade city dataset with Maharashtra deep-modeled
"""

CITIES = {
    # ─── MAHARASHTRA ───────────────────────────────────────────────
    "Mumbai_CST": {
        "display": "Mumbai — CST", "state": "Maharashtra", "country": "India",
        "lat": 18.9402, "lon": 72.8356,
        "area_type": "railway_station", "population_density": 95,
        "openaq_city": "Mumbai", "owm_city": "Mumbai",
        "zones": ["Marine Lines", "Fort", "CST", "Churchgate"],
        "infrastructure_load_base": 88,
    },
    "Mumbai_Dadar": {
        "display": "Dadar", "state": "Maharashtra", "country": "India",
        "lat": 19.0178, "lon": 72.8478,
        "area_type": "railway_station", "population_density": 97,
        "openaq_city": "Mumbai", "owm_city": "Mumbai",
        "zones": ["Dadar East", "Dadar West", "Shivaji Park", "Parel"],
        "infrastructure_load_base": 92,
    },
    "Mumbai_Andheri": {
        "display": "Andheri", "state": "Maharashtra", "country": "India",
        "lat": 19.1136, "lon": 72.8697,
        "area_type": "business_zone", "population_density": 89,
        "openaq_city": "Mumbai", "owm_city": "Mumbai",
        "zones": ["Andheri East", "Andheri West", "SEEPZ", "Versova"],
        "infrastructure_load_base": 85,
    },
    "Mumbai_Bandra": {
        "display": "Bandra", "state": "Maharashtra", "country": "India",
        "lat": 19.0596, "lon": 72.8295,
        "area_type": "mixed_zone", "population_density": 82,
        "openaq_city": "Mumbai", "owm_city": "Mumbai",
        "zones": ["Bandra West", "Bandra East", "BKC", "Khar"],
        "infrastructure_load_base": 80,
    },
    "Thane": {
        "display": "Thane", "state": "Maharashtra", "country": "India",
        "lat": 19.2183, "lon": 72.9781,
        "area_type": "residential", "population_density": 75,
        "openaq_city": "Thane", "owm_city": "Thane",
        "zones": ["Thane West", "Thane East", "Kopri", "Wagle Estate"],
        "infrastructure_load_base": 72,
    },
    "Kalyan": {
        "display": "Kalyan", "state": "Maharashtra", "country": "India",
        "lat": 19.2437, "lon": 73.1355,
        "area_type": "railway_station", "population_density": 78,
        "openaq_city": "Kalyan", "owm_city": "Kalyan",
        "zones": ["Kalyan West", "Kalyan East", "Tilaknagar", "Sahajanandnagar"],
        "infrastructure_load_base": 76,
    },
    "Dombivli": {
        "display": "Dombivli", "state": "Maharashtra", "country": "India",
        "lat": 19.2166, "lon": 73.0858,
        "area_type": "residential", "population_density": 73,
        "openaq_city": "Kalyan", "owm_city": "Dombivli",
        "zones": ["Dombivli East", "Dombivli West", "Manpada", "Sagaon"],
        "infrastructure_load_base": 70,
    },
    "Pune": {
        "display": "Pune", "state": "Maharashtra", "country": "India",
        "lat": 18.5204, "lon": 73.8567,
        "area_type": "business_zone", "population_density": 72,
        "openaq_city": "Pune", "owm_city": "Pune",
        "zones": ["Shivajinagar", "Koregaon Park", "Hadapsar", "Kothrud"],
        "infrastructure_load_base": 69,
    },
    "Nagpur": {
        "display": "Nagpur", "state": "Maharashtra", "country": "India",
        "lat": 21.1458, "lon": 79.0882,
        "area_type": "mixed_zone", "population_density": 60,
        "openaq_city": "Nagpur", "owm_city": "Nagpur",
        "zones": ["Sitabuldi", "Dharampeth", "Sadar", "Hingna"],
        "infrastructure_load_base": 58,
    },
    "Nashik": {
        "display": "Nashik", "state": "Maharashtra", "country": "India",
        "lat": 19.9975, "lon": 73.7898,
        "area_type": "mixed_zone", "population_density": 55,
        "openaq_city": "Nashik", "owm_city": "Nashik",
        "zones": ["Nashik Road", "Gangapur Road", "Panchavati", "MIDC"],
        "infrastructure_load_base": 52,
    },
    "Aurangabad": {
        "display": "Aurangabad", "state": "Maharashtra", "country": "India",
        "lat": 19.8762, "lon": 75.3433,
        "area_type": "mixed_zone", "population_density": 50,
        "openaq_city": "Aurangabad", "owm_city": "Aurangabad",
        "zones": ["CIDCO", "Garkheda", "N-7", "Osmanpura"],
        "infrastructure_load_base": 48,
    },
    "Navi_Mumbai": {
        "display": "Navi Mumbai", "state": "Maharashtra", "country": "India",
        "lat": 19.0330, "lon": 73.0297,
        "area_type": "planned_zone", "population_density": 65,
        "openaq_city": "Mumbai", "owm_city": "Navi Mumbai",
        "zones": ["Vashi", "Nerul", "Belapur", "Airoli"],
        "infrastructure_load_base": 62,
    },

    # ─── MAJOR INDIAN CITIES ─────────────────────────────────────
    "Delhi_CP": {
        "display": "Delhi — Connaught Place", "state": "Delhi", "country": "India",
        "lat": 28.6315, "lon": 77.2167,
        "area_type": "business_zone", "population_density": 93,
        "openaq_city": "Delhi", "owm_city": "New Delhi",
        "zones": ["CP Inner Ring", "CP Outer Ring", "Kashmere Gate", "ITO"],
        "infrastructure_load_base": 91,
    },
    "Delhi_Chandni_Chowk": {
        "display": "Chandni Chowk", "state": "Delhi", "country": "India",
        "lat": 28.6506, "lon": 77.2303,
        "area_type": "railway_station", "population_density": 98,
        "openaq_city": "Delhi", "owm_city": "New Delhi",
        "zones": ["Old Delhi", "Sadar Bazar", "Daryaganj", "Paharganj"],
        "infrastructure_load_base": 95,
    },
    "Bengaluru": {
        "display": "Bengaluru", "state": "Karnataka", "country": "India",
        "lat": 12.9716, "lon": 77.5946,
        "area_type": "business_zone", "population_density": 80,
        "openaq_city": "Bengaluru", "owm_city": "Bangalore",
        "zones": ["MG Road", "Whitefield", "Electronic City", "Koramangala"],
        "infrastructure_load_base": 78,
    },
    "Kolkata": {
        "display": "Kolkata", "state": "West Bengal", "country": "India",
        "lat": 22.5726, "lon": 88.3639,
        "area_type": "mixed_zone", "population_density": 88,
        "openaq_city": "Kolkata", "owm_city": "Kolkata",
        "zones": ["Howrah", "Park Street", "Salt Lake", "Dumdum"],
        "infrastructure_load_base": 84,
    },
    "Chennai": {
        "display": "Chennai", "state": "Tamil Nadu", "country": "India",
        "lat": 13.0827, "lon": 80.2707,
        "area_type": "business_zone", "population_density": 76,
        "openaq_city": "Chennai", "owm_city": "Chennai",
        "zones": ["T. Nagar", "Anna Nagar", "Adyar", "Tambaram"],
        "infrastructure_load_base": 73,
    },
    "Hyderabad": {
        "display": "Hyderabad", "state": "Telangana", "country": "India",
        "lat": 17.3850, "lon": 78.4867,
        "area_type": "business_zone", "population_density": 71,
        "openaq_city": "Hyderabad", "owm_city": "Hyderabad",
        "zones": ["Hitech City", "Banjara Hills", "Secunderabad", "LB Nagar"],
        "infrastructure_load_base": 69,
    },
    "Ahmedabad": {
        "display": "Ahmedabad", "state": "Gujarat", "country": "India",
        "lat": 23.0225, "lon": 72.5714,
        "area_type": "mixed_zone", "population_density": 67,
        "openaq_city": "Ahmedabad", "owm_city": "Ahmedabad",
        "zones": ["CG Road", "SG Highway", "Naroda", "Vastral"],
        "infrastructure_load_base": 64,
    },
    "Jaipur": {
        "display": "Jaipur", "state": "Rajasthan", "country": "India",
        "lat": 26.9124, "lon": 75.7873,
        "area_type": "mixed_zone", "population_density": 58,
        "openaq_city": "Jaipur", "owm_city": "Jaipur",
        "zones": ["Pink City", "Malviya Nagar", "Mansarovar", "Vaishali Nagar"],
        "infrastructure_load_base": 55,
    },
    "Lucknow": {
        "display": "Lucknow", "state": "Uttar Pradesh", "country": "India",
        "lat": 26.8467, "lon": 80.9462,
        "area_type": "mixed_zone", "population_density": 62,
        "openaq_city": "Lucknow", "owm_city": "Lucknow",
        "zones": ["Hazratganj", "Gomti Nagar", "Charbagh", "Aliganj"],
        "infrastructure_load_base": 60,
    },
    "Kanpur": {
        "display": "Kanpur", "state": "Uttar Pradesh", "country": "India",
        "lat": 26.4499, "lon": 80.3319,
        "area_type": "industrial", "population_density": 65,
        "openaq_city": "Kanpur", "owm_city": "Kanpur",
        "zones": ["Govind Nagar", "Armapur", "Kakadeo", "Swaroop Nagar"],
        "infrastructure_load_base": 63,
    },
    "Surat": {
        "display": "Surat", "state": "Gujarat", "country": "India",
        "lat": 21.1702, "lon": 72.8311,
        "area_type": "industrial", "population_density": 69,
        "openaq_city": "Surat", "owm_city": "Surat",
        "zones": ["Ring Road", "Adajan", "Varachha", "Katargam"],
        "infrastructure_load_base": 66,
    },
    "Bhopal": {
        "display": "Bhopal", "state": "Madhya Pradesh", "country": "India",
        "lat": 23.2599, "lon": 77.4126,
        "area_type": "mixed_zone", "population_density": 53,
        "openaq_city": "Bhopal", "owm_city": "Bhopal",
        "zones": ["MP Nagar", "Arera Colony", "TT Nagar", "Habibganj"],
        "infrastructure_load_base": 50,
    },
    "Patna": {
        "display": "Patna", "state": "Bihar", "country": "India",
        "lat": 25.5941, "lon": 85.1376,
        "area_type": "mixed_zone", "population_density": 70,
        "openaq_city": "Patna", "owm_city": "Patna",
        "zones": ["Gandhi Maidan", "Boring Road", "Rajendra Nagar", "Danapur"],
        "infrastructure_load_base": 68,
    },

    # ─── GLOBAL CITIES ───────────────────────────────────────────
    "Tokyo_Shinjuku": {
        "display": "Tokyo — Shinjuku", "state": "Tokyo", "country": "Japan",
        "lat": 35.6938, "lon": 139.7036,
        "area_type": "railway_station", "population_density": 96,
        "openaq_city": "Tokyo", "owm_city": "Tokyo",
        "zones": ["Kabukicho", "West Exit", "South Exit", "Shinjuku-gyoen"],
        "infrastructure_load_base": 93,
    },
    "London_Waterloo": {
        "display": "London — Waterloo", "state": "England", "country": "UK",
        "lat": 51.5031, "lon": -0.1132,
        "area_type": "railway_station", "population_density": 82,
        "openaq_city": "London", "owm_city": "London",
        "zones": ["Waterloo", "Lambeth", "Southbank", "Elephant & Castle"],
        "infrastructure_load_base": 79,
    },
    "NYC_Manhattan": {
        "display": "New York — Manhattan", "state": "New York", "country": "USA",
        "lat": 40.7580, "lon": -73.9855,
        "area_type": "business_zone", "population_density": 91,
        "openaq_city": "New York", "owm_city": "New York",
        "zones": ["Times Square", "Midtown", "Financial District", "Upper East Side"],
        "infrastructure_load_base": 87,
    },
    "Beijing": {
        "display": "Beijing", "state": "Beijing", "country": "China",
        "lat": 39.9042, "lon": 116.4074,
        "area_type": "business_zone", "population_density": 85,
        "openaq_city": "Beijing", "owm_city": "Beijing",
        "zones": ["Chaoyang", "Haidian", "Dongcheng", "Xicheng"],
        "infrastructure_load_base": 82,
    },
    "Shanghai": {
        "display": "Shanghai", "state": "Shanghai", "country": "China",
        "lat": 31.2304, "lon": 121.4737,
        "area_type": "business_zone", "population_density": 88,
        "openaq_city": "Shanghai", "owm_city": "Shanghai",
        "zones": ["Pudong", "Huangpu", "Jing'an", "Xuhui"],
        "infrastructure_load_base": 85,
    },
    "Singapore": {
        "display": "Singapore", "state": "Central", "country": "Singapore",
        "lat": 1.3521, "lon": 103.8198,
        "area_type": "business_zone", "population_density": 78,
        "openaq_city": "Singapore", "owm_city": "Singapore",
        "zones": ["CBD", "Orchard", "Jurong", "Tampines"],
        "infrastructure_load_base": 72,
    },
    "Dubai": {
        "display": "Dubai", "state": "Dubai", "country": "UAE",
        "lat": 25.2048, "lon": 55.2708,
        "area_type": "business_zone", "population_density": 74,
        "openaq_city": "Dubai", "owm_city": "Dubai",
        "zones": ["Downtown", "Marina", "DIFC", "Deira"],
        "infrastructure_load_base": 70,
    },
    "Sydney": {
        "display": "Sydney", "state": "NSW", "country": "Australia",
        "lat": -33.8688, "lon": 151.2093,
        "area_type": "business_zone", "population_density": 62,
        "openaq_city": "Sydney", "owm_city": "Sydney",
        "zones": ["CBD", "Parramatta", "Bondi", "Chatswood"],
        "infrastructure_load_base": 59,
    },
    "Paris": {
        "display": "Paris", "state": "Île-de-France", "country": "France",
        "lat": 48.8566, "lon": 2.3522,
        "area_type": "business_zone", "population_density": 83,
        "openaq_city": "Paris", "owm_city": "Paris",
        "zones": ["1st", "8th", "La Défense", "Saint-Denis"],
        "infrastructure_load_base": 80,
    },
    "Berlin": {
        "display": "Berlin", "state": "Berlin", "country": "Germany",
        "lat": 52.5200, "lon": 13.4050,
        "area_type": "business_zone", "population_density": 65,
        "openaq_city": "Berlin", "owm_city": "Berlin",
        "zones": ["Mitte", "Friedrichshain", "Prenzlauer Berg", "Charlottenburg"],
        "infrastructure_load_base": 62,
    },
    "Toronto": {
        "display": "Toronto", "state": "Ontario", "country": "Canada",
        "lat": 43.6532, "lon": -79.3832,
        "area_type": "business_zone", "population_density": 68,
        "openaq_city": "Toronto", "owm_city": "Toronto",
        "zones": ["Downtown Core", "North York", "Scarborough", "Etobicoke"],
        "infrastructure_load_base": 65,
    },
    "Jakarta": {
        "display": "Jakarta", "state": "DKI Jakarta", "country": "Indonesia",
        "lat": -6.2088, "lon": 106.8456,
        "area_type": "business_zone", "population_density": 90,
        "openaq_city": "Jakarta", "owm_city": "Jakarta",
        "zones": ["Central Jakarta", "South Jakarta", "North Jakarta", "Tangerang"],
        "infrastructure_load_base": 88,
    },
    "Bangkok": {
        "display": "Bangkok", "state": "Bangkok", "country": "Thailand",
        "lat": 13.7563, "lon": 100.5018,
        "area_type": "mixed_zone", "population_density": 84,
        "openaq_city": "Bangkok", "owm_city": "Bangkok",
        "zones": ["Sukhumvit", "Silom", "Rattanakosin", "Din Daeng"],
        "infrastructure_load_base": 81,
    },
    "Seoul": {
        "display": "Seoul", "state": "Seoul", "country": "South Korea",
        "lat": 37.5665, "lon": 126.9780,
        "area_type": "business_zone", "population_density": 87,
        "openaq_city": "Seoul", "owm_city": "Seoul",
        "zones": ["Gangnam", "Jung-gu", "Mapo", "Nowon"],
        "infrastructure_load_base": 84,
    },
    "Dhaka": {
        "display": "Dhaka", "state": "Dhaka", "country": "Bangladesh",
        "lat": 23.8103, "lon": 90.4125,
        "area_type": "mixed_zone", "population_density": 99,
        "openaq_city": "Dhaka", "owm_city": "Dhaka",
        "zones": ["Motijheel", "Gulshan", "Mirpur", "Uttara"],
        "infrastructure_load_base": 97,
    },
    "Karachi": {
        "display": "Karachi", "state": "Sindh", "country": "Pakistan",
        "lat": 24.8607, "lon": 67.0011,
        "area_type": "mixed_zone", "population_density": 92,
        "openaq_city": "Karachi", "owm_city": "Karachi",
        "zones": ["Saddar", "DHA", "Gulshan", "Korangi"],
        "infrastructure_load_base": 90,
    },
    "Lagos": {
        "display": "Lagos", "state": "Lagos", "country": "Nigeria",
        "lat": 6.5244, "lon": 3.3792,
        "area_type": "mixed_zone", "population_density": 94,
        "openaq_city": "Lagos", "owm_city": "Lagos",
        "zones": ["Victoria Island", "Ikeja", "Lekki", "Surulere"],
        "infrastructure_load_base": 92,
    },
    "Cairo": {
        "display": "Cairo", "state": "Cairo", "country": "Egypt",
        "lat": 30.0444, "lon": 31.2357,
        "area_type": "mixed_zone", "population_density": 86,
        "openaq_city": "Cairo", "owm_city": "Cairo",
        "zones": ["Downtown", "Nasr City", "Heliopolis", "6th October"],
        "infrastructure_load_base": 84,
    },
    "São_Paulo": {
        "display": "São Paulo", "state": "São Paulo", "country": "Brazil",
        "lat": -23.5505, "lon": -46.6333,
        "area_type": "business_zone", "population_density": 89,
        "openaq_city": "Sao Paulo", "owm_city": "São Paulo",
        "zones": ["Centro", "Paulista", "Berrini", "Morumbi"],
        "infrastructure_load_base": 86,
    },
    "Mexico_City": {
        "display": "Mexico City", "state": "CDMX", "country": "Mexico",
        "lat": 19.4326, "lon": -99.1332,
        "area_type": "mixed_zone", "population_density": 87,
        "openaq_city": "Mexico City", "owm_city": "Mexico City",
        "zones": ["Centro Histórico", "Santa Fe", "Polanco", "Tlalpan"],
        "infrastructure_load_base": 84,
    },
}

# Area type → peak hour profiles
AREA_PEAK_PROFILES = {
    "railway_station": {
        "peaks": [(7, 10), (17, 21)],
        "base_crowd": 60,
        "peak_multiplier": 1.7,
        "off_peak_multiplier": 0.5,
    },
    "business_zone": {
        "peaks": [(8, 10), (18, 20)],
        "base_crowd": 45,
        "peak_multiplier": 1.6,
        "off_peak_multiplier": 0.3,
    },
    "residential": {
        "peaks": [(7, 9), (19, 22)],
        "base_crowd": 30,
        "peak_multiplier": 1.3,
        "off_peak_multiplier": 0.7,
    },
    "mixed_zone": {
        "peaks": [(8, 11), (17, 20)],
        "base_crowd": 40,
        "peak_multiplier": 1.5,
        "off_peak_multiplier": 0.45,
    },
    "industrial": {
        "peaks": [(6, 9), (16, 19)],
        "base_crowd": 35,
        "peak_multiplier": 1.4,
        "off_peak_multiplier": 0.4,
    },
    "planned_zone": {
        "peaks": [(8, 10), (18, 21)],
        "base_crowd": 35,
        "peak_multiplier": 1.4,
        "off_peak_multiplier": 0.4,
    },
}

# UPI thresholds
UPI_THRESHOLDS = {
    "Low": (0, 30),
    "Moderate": (30, 55),
    "High": (55, 75),
    "Extreme": (75, 100),
}

UPI_COLORS = {
    "Low": "#22c55e",
    "Moderate": "#eab308",
    "High": "#f97316",
    "Extreme": "#ef4444",
}

ALERT_THRESHOLD = 75  # UPI score to trigger alert
